apiVersion: github.example.org/v1alpha1
kind: RepoClaim
metadata:
  name: demo-repo-three
spec:
  name: gitops-crossplane-demo-three
  description: "A demo repo created via GitOps claim with crossplane"
  private: false
  autoInit: true